import Head from "next/head";
import { useContext } from "react";
import Feed from "../components/Feed";
import { AuthContext } from "../context/auth";
import { useRouter } from "next/router";

export default function Home() {
  const { user } = useContext(AuthContext);

  const Redirect = () => {
    const router = useRouter();
    router.push("/login");
    return null;
  };
  return (
    <div>
      <Head>
        <title>Instagram Reels</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://seeklogo.com/images/I/instagram-logo-A807AD378B-seeklogo.com.png"
        />
      </Head>
      {user?.uid ? <Feed /> : <Redirect />}
    </div>
  );
}
