import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Instagram Reels</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://seeklogo.com/images/I/instagram-logo-A807AD378B-seeklogo.com.png" />
      </Head>

     Hello Sahil

    
    </div>
  )
}
