import Head from "next/head";
import Feed from "../components/Feed";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Instagram Reels</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://seeklogo.com/images/I/instagram-logo-A807AD378B-seeklogo.com.png"
        />
      </Head>
      <Feed />
    </div>
  );
}
